[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

# parse_string prep
[[patches]]
[patches.pattern]
target = 'afunctions/common_events.lua'
pattern = "if card == nil and card_type then"
position = 'before'
match_indent = false
payload = '''
    local function prep_specific_vars ()
        if SMODS then
            specific_vars = specific_vars or {}
            specific_vars.elements = {}
            for _,v in ipairs(Icons.get_needed_icons(_c)) do
                table.insert(
                    specific_vars.elements,
                    { n=G.UIT.C, config = { align="cm" }, nodes = { 
                        { n=G.UIT.O, config= { object =
                            SMODS.create_sprite(0, 0, 0.3, 0.3, v.atlas ~= false and v.atlas or 'ico_icons', v.pos or {x = 0, y = 0})
                        } }
                    } }
                )
            end
        end
    end
    local function transfer_loc_vars ()
        specific_vars = _c.vars or loc_vars
        prep_specific_vars()
        _c.vars = specific_vars
        loc_vars = specific_vars
    end
'''
